FORMAT: 1A

# Swapped API

This is a simple API to develop Swapped 0.1

## SignIn [/api/signIn]

### POST

+ Request (application/json)
        {
            "fullname" : "rafael camargos santos",
            "password" : "qwertyui",
            "email" : "rafael.appsimples@gmail.com",
            "account" : "rcamargos"
        }

+ Response 200 (application/json)
        
        {
          "success": true,
          "message": "Usuário cadastrado com sucesso!"
        }


## SignIn Fail [/api/signIn-fail]

### POST

+ Response 200 (application/json)
        
        {
          "success": false,
          "message": "Email já cadastrado."
        }

+ Response 200 (application/json)
        
        {
          "success": false,
          "message": "Usuário já cadastrado."
        }


## Login [/login]

### POST

+ Request (application/json)

        {
            "account" : "rcamargos",
            "password" : "qwertyui"
        }

+ Response 200 (application/json)

    + Body

            {
              "success": true,
              "message": "sucesso no login.",
              "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NzAyOGEzY2ZiZGM0MDJmYTMzMzNiZjMiLCJhY2NvdW50IjoicmNhbWFyZ29zIiwiZW1haWwiOiJyYWZhZWwuYXBwc2ltcGxlc0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNCRiWEN6d0JMTENNWW9vUTNmdDB0VkllQ2ExbDJVcEJiOFFxdHV2bHFFQkVFV2tKR2RFT2svZSIsInVzZXJJRCI6IjU3MDI4YTNjZmJkYzQwMmZhMzMzM2JmMiIsIl9fdiI6MCwiaWF0IjoxNDU5Nzg4MDk1LCJleHAiOjE0NTk4NzQ0OTV9.XbL2tpxS7OONC-2s9nQWPHzo4awtM2rshYpAfmTCDlw",
              "userID": "57028a3cfbdc402fa3333bf2"
            }

## Login Fail [/login-fail]

### POST

+ Request (application/json)

        {
            "email": "rcamargos",
            "senha": "errada"
        }

+ Response 401 (application/json)

    + Body

            {
              "success": false,
              "message": "Falha na autenticação. Senha incorreta."
            }

## Change Password [/api/changePassword]

### POST

+ Request (application/json)

        {
            "userID" : "57029d026c306e31a5aa2835",
            "password" : "qwertyui",
            "newPassword" : "qwertyui"
        }

+ Response 401 (application/json)

    + Body

            {
              "success": true,
              "message": "Senha alterada com sucesso!"
            }
